export const githubEventTypes = Object.freeze({
  CheckRunEvent: "CheckRunEvent",
  CheckSuiteEvent: "CheckSuiteEvent",
  CommitCommentEvent: "CommitCommentEvent",
  ContentReferenceEvent:"ContentReferenceEvent",
  CreateEvent:"CreateEvent",
  DeleteEvent:"DeleteEvent",
  DeployKeyEvent:"DeployKeyEvent",
  DeploymentEvent:"DeploymentEvent",
  DeploymentStatusEvent:"DeploymentStatusEvent",
  DownloadEvent:"DownloadEvent",
  FollowEvent:"FollowEvent",
  ForkEvent:"ForkEvent",
  ForkApplyEvent:"ForkApplyEvent",
  GitHubAppAuthorizationEvent:"GitHubAppAuthorizationEvent",
  GistEvent:"GistEvent",
  GollumEvent:"GollumEvent",
  InstallationEvent:"InstallationEvent",
  InstallationRepositoriesEvent:"InstallationRepositoriesEvent",
  IssueCommentEvent:"IssueCommentEvent",
  IssuesEvent:"IssuesEvent",
  LabelEvent:"LabelEvent",
  MarketplacePurchaseEvent:"MarketplacePurchaseEvent",
  MemberEvent:"MemberEvent",
  MembershipEvent:"MembershipEvent",
  MetaEvent:"MetaEvent",
  MilestoneEvent:"MilestoneEvent",
  OrganizationEvent:"OrganizationEvent",
  OrgBlockEvent:"OrgBlockEvent",
  PageBuildEvent:"PageBuildEvent",
  ProjectCardEvent:"ProjectCardEvent",
  ProjectColumnEvent:"ProjectColumnEvent",
  ProjectEvent:"ProjectEvent",
  PublicEvent:"PublicEvent",
  PullRequestEvent:"PullRequestEvent",
  PullRequestReviewEvent:"PullRequestReviewEvent",
  PullRequestReviewCommentEvent:"PullRequestReviewCommentEvent",
  PushEvent:"PushEvent",
  RegistryPackageEvent:"RegistryPackageEvent",
  ReleaseEvent:"ReleaseEvent",
  RepositoryEvent:"RepositoryEvent",
  RepositoryImportEvent:"RepositoryImportEvent",
  RepositoryVulnerabilityAlertEvent:"RepositoryVulnerabilityAlertEvent",
  SecurityAdvisoryEvent:"SecurityAdvisoryEvent",
  StarEvent:"StarEvent",
  StatusEvent:"StatusEvent",
  TeamEvent:"TeamEvent",
  TeamAddEvent:"TeamAddEvent",
  WatchEvent:"WatchEvent",


});